spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/churn_prediction
    username: postgres
    password: Kasar@625
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.PostgreSQLDialect
